spring.datasource.url=jdbc:postgresql://localhost:5432/bookwise
spring.datasource.username=bookwise
spring.datasource.password=bookwise
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.security.user.name=demo@bookwise.local
spring.security.user.password=demo123
spring.security.user.roles=USER