spring.application.name=bookwise-api

spring.datasource.url=jdbc:postgresql://localhost:5432/bookwise
spring.datasource.username=bookwise
spring.datasource.password=bookwise
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true